openapi: 3.0.3
info:
  title: 個人資訊 API
  version: 1.0.1
  description: 提供使用者的個人資訊，回傳格式為 JSend。

servers:
  - url: http://localhost:3000/api

paths:
  /my:
    get:
      summary: 取得個人資訊
      description: 回傳使用者的個人資訊，包含姓名、信箱、學校、科系、階段與論文最後提交時間。
      responses:
        '200':
          description: 成功回傳個人資訊
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSendSuccessUser'
        '400':
          description: 請求錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSendFail'
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSendError'

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          example: 王小明
        email:
          type: string
          format: email
          example: test@example.com
        school:
          type: string
          example: 國立台灣大學
        department:
          type: string
          example: 資訊工程學系
        stage:
          type: integer
          minimum: 1
          maximum: 5
          example: 4
        thesisSubmittedAt:
          type: string
          format: date-time
          description: 論文最後提交時間 (ISO 8601 格式)
          example: "2025-08-20T14:30:00Z"

    JSendSuccessUser:
      type: object
      properties:
        status:
          type: string
          enum: [success]
          example: success
        data:
          $ref: '#/components/schemas/User'

    JSendFail:
      type: object
      properties:
        status:
          type: string
          enum: [fail]
          example: fail
        data:
          type: object
          additionalProperties: true
          example:
            message: 缺少必要參數

    JSendError:
      type: object
      properties:
        status:
          type: string
          enum: [error]
          example: error
        message:
          type: string
          example: 伺服器發生錯誤
        code:
          type: integer
          example: 500


