openapi: 3.0.3
info:
  title: 國圖論文上傳 FAQ API
  version: 1.0.0
  description: 取得常見問答清單 API（JSend 格式）

servers:
  - url: http://localhost:3000/api

paths:
  /static/faqs:
    get:
      summary: 取得常見問答清單
      responses:
        '200':
          description: FAQ 列表
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - data
                properties:
                  status:
                    type: string
                    enum: [success]
                    example: "success"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        question:
                          type: string
                          example: "如何上傳論文？"
                        answer:
                          type: string
                          example: "請點選『進入上傳系統』，依照指示完成論文上傳流程。"

  /api/static/docs:
    get:
      summary: 取得所有文件類別及其檔案清單
      responses:
        '200':
          description: 文件類別與檔案清單
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - data
                properties:
                  status:
                    type: string
                    enum: [success]
                    example: "success"
                  data:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - name
                        - files
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: "上傳說明"
                        files:
                          type: array
                          items:
                            type: object
                            required:
                              - id
                              - name
                              - url
                            properties:
                              id:
                                type: integer
                                example: 101
                              name:
                                type: string
                                example: "論文上傳說明.pdf"
                              url:
                                type: string
                                example: "https://example.com/files/101/download"
