openapi: 3.0.3
info:
  title: 國圖論文上傳 API
  version: 1.0.0
  description: 學位論文上傳流程 API（JSend 格式）

servers:
  - url: http://localhost:3000/api

paths:
  /thesis/uploadFile:
    post:
      summary: 上傳論文主檔與補充資料
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                thesisFile:
                  type: string
                  format: binary
                  description: 論文 PDF 主檔
                attachments:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: 補充資料（圖片、程式碼、附檔等）
      responses:
        '200':
          description: 上傳成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, enum: [success] }
                  data:
                    type: object
                    properties:
                      uploadId: { type: string, example: "abc123" }

  /thesis/submit:
    post:
      summary: 上傳論文相關文字資料（學籍 / 論文資料 / 摘要 / 目錄 / 參考文獻）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                student:
                  type: object
                  properties:
                    school: { type: string, example: "國立台北科技大學" }
                    department: { type: string, example: "資訊工程系" }
                    degree: { type: string, example: "碩士" }
                    academicYear: { type: string, example: "113年度" }
                    nameZh: { type: string, example: "陳小明" }
                    nameEn: { type: string, example: "CHEN, SIAO-MING" }
                    studentId: { type: string, example: "M110123456" }
                thesis:
                  type: object
                  properties:
                    titleZh: { type: string, example: "我的論文題目" }
                    titleEn: { type: string, example: "My thesis title" }
                    advisor: { type: string }
                    advisorEn: { type: string }
                    committee: { type: array, items: { type: string } }
                    language: { type: string }
                    pageCount: { type: integer }
                    referenceCount: { type: integer }
                abstract:
                  type: object
                  properties:
                    abstractZh: { type: string }
                    abstractEn: { type: string }
                    keywordsZh: { type: array, items: { type: string } }
                    keywordsEn: { type: array, items: { type: string } }
                toc:
                  type: string
                  example: "目錄的 markdown"
                references:
                  type: string
                  example: "參考文獻的 markdown"
      responses:
        '200':
          description: 資料儲存成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, enum: [success] }
                  data:
                    type: object
                    properties:
                      thesisId: { type: string, example: "thesis-001" }

  /thesis/authorization:
    post:
      summary: 設定論文授權與公開方式
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                schoolAuthorization:
                  type: object
                  description: 對學校授權
                  properties:
                    mode:
                      type: string
                      enum: ["agree", "saveOnly"]
                      example: "agree"
                    scope:
                      type: string
                      enum: ["campus", "global"]
                      example: "campus"
                nclAuthorization:
                  type: object
                  description: 對國家圖書館授權
                  properties:
                    mode:
                      type: string
                      enum: ["agree", "saveOnly"]
                      example: "agree"
                thirdPartyAuthorization:
                  type: object
                  description: 對第三方資料庫授權
                  properties:
                    mode:
                      type: string
                      enum: ["paid", "free", "deny"]
                      example: "deny"
                publishSetting:
                  type: object
                  description: 延伸公開設定
                  properties:
                    mode:
                      type: string
                      enum: ["immediate", "delayed"]
                      example: "immediate"
      responses:
        '200':
          description: 儲存成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                    example: "success"
                  data:
                    type: object
                    properties:
                      thesisId:
                        type: string
                        example: "thesis-001"


  /thesis/rejections:
    get:
      summary: 取得退件理由
      description: 取得使用者論文退件的歷史紀錄，包含退件日期、審查員、退件原因與標記。
      responses:
        '200':
          description: 成功回傳退件紀錄
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                    example: success
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                          example: "2025-07-18"
                        reviewer:
                          type: string
                          example: "國家圖書館 王審查員"
                        reasons:
                          type: array
                          items:
                            type: string
                          example:
                            - 論文資料不完整：缺少中文標題、英文標題、教授名稱、目錄、頁數或參考文獻
                            - 頁面標記錯誤
                        notes:
                          type: string
                          example: "輸入錯誤原因輸入錯誤原因輸入錯誤原因..."
                        status:
                          type: string
                          enum: [已退件, 已核准]
                          example: 已退件
        '400':
          description: 請求錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [fail]
                    example: fail
                  data:
                    type: object
                    additionalProperties: true
                    example:
                      message: 缺少必要參數



  /thesis/replace:
    post:
      summary: 提交論文更換/補充申請
      description: 學生可提交修改內容簡述與指導教授同意證明文件，送交系統審核，成功後可重新上傳論文檔案。
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: 修改內容簡述
                  example: 修正論文標題與補充缺少的參考文獻
                approvalFile:
                  type: string
                  format: binary
                  description: 指導教授同意證明文件 (PDF, JPG, PNG)
      responses:
        '200':
          description: 申請成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                    example: success
                  data:
                    type: object
                    properties:
                      requestId:
                        type: string
                        example: "REQ-20250822-001"
                      submittedAt:
                        type: string
                        format: date-time
                        example: "2025-08-22T07:45:00Z"
                      message:
                        type: string
                        example: 申請已送出，請等待系統審核
        '400':
          description: 請求錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [fail]
                    example: fail
                  data:
                    type: object
                    example:
                      message: 缺少必要參數 (description 或 approvalFile)
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [error]
                    example: error
                  message:
                    type: string
                    example: 系統發生錯誤，請稍後再試
                  code:
                    type: integer
                    example: 500
