openapi: 3.0.3
info:
  title: 「新世代博碩士論文網」最新公告 API (Cloudflare 風格)
  description: 提供最新公告列表與公告詳細內容，回應結構採 Cloudflare API 慣例
  version: 1.0.0
servers:
  - url: https://ndltd.ncl.edu.tw/api/v1
paths:
  /announcements:
    get:
      summary: 取得最新公告列表
      description: 取得最新公告，顯示短內容 summary
      parameters:
        - name: page
          in: query
          description: 分頁頁碼（預設為 1）
          required: false
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          description: 每頁筆數（預設為 10）
          required: false
          schema:
            type: integer
            default: 10
        - name: type
          in: query
          description: 公告分類（系統公告、最新消息）
          required: false
          schema:
            type: string
            enum: [系統公告, 最新消息]
        - name: tag
          in: query
          description: 公告標籤（重要、新功能），可多選（以逗號分隔）
          required: false
          schema:
            type: string
            example: "重要,新功能"
      responses:
        '200':
          description: 成功取得公告列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  errors:
                    type: array
                    items:
                      type: object
                    example: []
                  messages:
                    type: array
                    items:
                      type: object
                    example: []
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "2024011501"
                        title:
                          type: string
                          example: "系統維護公告"
                        type:
                          type: string
                          example: "系統公告"
                        tags:
                          type: array
                          items:
                            type: string
                          example: ["重要"]
                        summary:
                          type: string
                          example: "2024/01/15 凌晨2:00-4:00 系統維護，暫停服務"
                        date:
                          type: string
                          format: date
                          example: "2024-01-15"
                  result_info:
                    type: object
                    properties:
                      page:
                        type: integer
                        example: 1
                      per_page:
                        type: integer
                        example: 10
                      count:
                        type: integer
                        example: 1
                      total_count:
                        type: integer
                        example: 200
        '400':
          description: 錯誤的請求參數
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: integer
                          example: 1001
                        message:
                          type: string
                          example: "Invalid query parameter"
                  messages:
                    type: array
                    items:
                      type: object
                    example: []
                  result:
                    nullable: true
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: integer
                          example: 1002
                        message:
                          type: string
                          example: "Internal server error"
                  messages:
                    type: array
                    items:
                      type: object
                    example: []
                  result:
                    nullable: true

  /announcements/{id}:
    get:
      summary: 取得公告詳細內容
      description: 依公告 id 取得完整公告內容
      parameters:
        - name: id
          in: path
          required: true
          description: 公告唯一識別碼
          schema:
            type: string
            example: "20240115"
      responses:
        '200':
          description: 成功取得公告詳細內容
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  errors:
                    type: array
                    items:
                      type: object
                    example: []
                  messages:
                    type: array
                    items:
                      type: object
                    example: []
                  result:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "20240115"
                      title:
                        type: string
                        example: "系統維護公告"
                      type:
                        type: string
                        example: "系統公告"
                      tags:
                        type: array
                        items:
                          type: string
                        example: ["重要"]
