# swagger.yaml

openapi: 3.0.3
info:
  title: Taiwan Thesis Pulse 研究成果上傳 API
  description: 研究成果上傳表單，支援網址/DOI或截圖方式
  version: 1.0.0
servers:
  - url: https://api.taiwan-thesis-pulse.lovable.app
paths:
  /api/research-result:
    post:
      summary: 上傳研究成果
      description: 提交研究成果資訊，支援網址/DOI或截圖方式
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - projectTitle
                - principalInvestigator
                - contactEmail
                - resultTitle
                - infoType
              properties:
                projectTitle:
                  type: string
                  description: 計畫標題
                  example: "台灣學術成果公開計畫"
                principalInvestigator:
                  type: string
                  description: 計畫主持人/指導教授
                  example: "王教授"
                contactEmail:
                  type: string
                  format: email
                  description: 聯絡信箱
                  example: "contact@example.com"
                contactPhone:
                  type: string
                  description: 聯絡電話
                  example: "0912345678"
                organization:
                  type: string
                  description: 服務機構
                  example: "國立臺灣大學"
                resultTitle:
                  type: string
                  description: 成果標題
                  example: "AI在論文檢索中的應用"
                infoType:
                  type: string
                  description: 提供成果資訊方式（url 或 screenshot）
                  enum: [url, screenshot]
                  example: "url"
                urlOrDOI:
                  type: string
                  description: 永久網址或 DOI（infoType=url 時必填）
                  example: "https://doi.org/10.1234/example"
                screenshot:
                  type: string
                  format: binary
                  description: 成果截圖主頁（infoType=screenshot 時必填）
                description:
                  type: string
                  description: 補充說明
                  example: "本成果已於國際期刊發表"
      responses:
        '201':
          description: 成功提交研究成果
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: 研究成果唯一識別碼
                    example: "abc123"
                  message:
                    type: string
                    description: 成功訊息
                    example: "研究成果已成功提交"
        '400':
          description: 表單資料錯誤或缺漏
        '500':
          description: 伺服器錯誤


  /api/upload/file:
    post:
      summary: 上傳檔案
      description: 上傳相關研究計畫書、IRB核准文件等，回傳檔案編號
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: 上傳檔案
      responses:
        '201':
          description: 成功上傳檔案
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileId:
                    type: string
                    description: 檔案唯一編號
                    example: "file_abc123"
                  message:
                    type: string
                    description: 成功訊息
                    example: "檔案已成功上傳"
        '400':
          description: 檔案格式錯誤或缺漏
        '500':
          description: 伺服器錯誤

  /api/bibliography-application:
    post:
      summary: 申請大量書目資料
      description: 提交申請人基本資料、處理人員資訊、書目需求、研究規劃、檔案編號與研究計畫申請情形
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - title
                - organization
                - idNumber
                - phone
                - email
                - unitType
                - researchType
                - staff
                - bibliography
                - researchPlan
              properties:
                name:
                  type: string
                  description: 申請人姓名
                  example: "王小明"
                title:
                  type: string
                  description: 職稱
                  example: "助理教授"
                organization:
                  type: string
                  description: 服務機構
                  example: "國立臺灣大學"
                idNumber:
                  type: string
                  description: 身分證號
                  example: "A123456789"
                phone:
                  type: string
                  description: 聯絡電話
                  example: "0912345678"
                email:
                  type: string
                  format: email
                  description: 電子郵件
                  example: "user@example.com"
                unitType:
                  type: string
                  description: 單位類別
                  example: "學術單位"
                projectStatus:
                  type: string
                  description: 研究計畫申請情形（已通過/申請中/未申請）
                  enum: [已通過, 申請中, 未申請]
                  example: "已通過"
                irbStatus:
                  type: string
                  description: IRB申請情形（已通過/申請中/未申請）
                  enum: [已通過, 申請中, 未申請]
                  example: "申請中"
                researchType:
                  type: string
                  description: 研究類型
                  example: "量化研究"
                staff:
                  type: array
                  description: 處理人員資訊
                  items:
                    type: object
                    required:
                      - name
                      - idNumber
                    properties:
                      name:
                        type: string
                        description: 處理人員姓名
                        example: "李小華"
                      idNumber:
                        type: string
                        description: 處理人員身分證號
                        example: "B987654321"
                      gender:
                        type: string
                        description: 性別
                        enum: [男, 女, 其他]
                        example: "男"
                      organization:
                        type: string
                        description: 服務機構
                        example: "國立成功大學"
                      title:
                        type: string
                        description: 職稱
                        example: "研究助理"
                      phone:
                        type: string
                        description: 聯絡電話
                        example: "0987654321"
                      email:
                        type: string
                        format: email
                        description: 電子郵件
                        example: "staff@example.com"
                bibliography:
                  type: object
                  description: 書目需求資訊
                  required:
                    - dataType
                    - startYear
                    - endYear
                    - disciplines
                    - fileFormats
                  properties:
                    dataType:
                      type: string
                      description: 資料類型（簡目/詳目）
                      enum: [簡目, 詳目]
                      example: "詳目"
                    startYear:
                      type: integer
                      description: 起始學年度
                      example: 110
                    endYear:
                      type: integer
                      description: 結束學年度
                      example: 113
                    disciplines:
                      type: array
                      description: 學門選擇（可多選）
                      items:
                        type: string
                      example:
                        - "教育學門"
                        - "工程學門"
                        - "醫藥衛生學門"
                    fileFormats:
                      type: array
                      description: 檔案格式（可多選）
                      items:
                        type: string
                        enum: [CSV, XLSX, JSON, ODF]
                      example:
                        - "CSV"
                        - "XLSX"
                researchPlan:
                  type: object
                  description: 研究規劃資訊
                  required:
                    - projectName
                    - background
                    - purpose
                    - method
                    - resultTypes
                  properties:
                    projectName:
                      type: string
                      description: 研究名稱
                      example: "台灣學術資料開放研究"
                    background:
                      type: string
                      description: 研究緣起
                      example: "因應學術資料開放趨勢..."
                    purpose:
                      type: string
                      description: 研究目的
                      example: "提升資料可用性與學術交流"
                    method:
                      type: string
                      description: 實施方法
                      example: "問卷調查與資料分析"
                    resultTypes:
                      type: array
                      description: 研究成果類型（可多選）
                      items:
                        type: string
                        enum: [會議論文, 期刊論文, 博碩士論文, 專書, 研究報告, 其他]
                      example:
                        - "期刊論文"
                        - "博碩士論文"
                    principalInvestigator:
                      type: string
                      description: 研究主持人資訊
                      example: "王教授"
                fileIds:
                  type: array
                  description: 已上傳檔案編號（可多個）
                  items:
                    type: string
                  example:
                    - "file_abc123"
                    - "file_def456"
      responses:
        '201':
          description: 成功提交申請
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: 申請唯一識別碼
                    example: "req_123456"
                  message:
                    type: string
                    description: 成功訊息
                    example: "申請已成功提交"
        '400':
          description: 表單資料錯誤或缺漏
        '500':
          description: 伺服器錯誤
components: {}

