# swagger.yaml

openapi: 3.0.3
info:
  title: Taiwan Thesis Pulse 博碩士論文熱門排行榜 API
  description: 提供臺灣博碩士論文熱門排行榜，支援排行類型、年度與筆數限制
  version: 1.1.0
servers:
  - url: https://api.taiwan-thesis-pulse.lovable.app
paths:
  /api/ranking/schools:
    get:
      summary: 取得博碩士論文熱門排行榜
      description: 取得各校熱門論文排行榜，支援排行類型、年度與筆數限制
      parameters:
        - name: type
          in: query
          description: 排行類型（全文授權 total、被引用數 reference、被點閱數 view、全文下載數 download）
          required: true
          schema:
            type: string
            enum: [total, reference, view, download]
        - name: year
          in: query
          description: 年度（如 113、112、111）
          required: false
          schema:
            type: integer
            example: 113
        - name: limit
          in: query
          description: 限制回傳最大筆數（預設 10，最大 100）
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
      responses:
        '200':
          description: 成功取得排行榜
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        rank:
                          type: integer
                          description: 排名
                          example: 1
                        school:
                          type: string
                          description: 學校名稱
                          example: "國立臺灣大學"
                        count:
                          type: integer
                          description: 數量
                          example: 12456

        '400':
          description: 錯誤的請求參數
        '500':
          description: 伺服器錯誤
  /api/ranking/professors:
    get:
      summary: 取得博碩士論文熱門排行榜
      description: 取得各校熱門論文排行榜，支援排行類型、年度與筆數限制
      parameters:
        - name: type
          in: query
          description: 排行類型（全文授權 total、被引用數 reference、被點閱數 view、全文下載數 download）
          required: true
          schema:
            type: string
            enum: [total, reference, view, download]
        - name: year
          in: query
          description: 年度（如 113、112、111）
          required: false
          schema:
            type: integer
            example: 113
        - name: limit
          in: query
          description: 限制回傳最大筆數（預設 10，最大 100）
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
      responses:
        '200':
          description: 成功取得排行榜
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        rank:
                          type: integer
                          description: 排名
                          example: 1
                        school:
                          type: string
                          description: 學校名稱
                          example: "國立臺灣大學"
                        count:
                          type: integer
                          description: 數量
                          example: 12456

        '400':
          description: 錯誤的請求參數
        '500':
          description: 伺服器錯誤
  /api/ranking/students:
    get:
      summary: 取得博碩士論文熱門排行榜
      description: 取得各校熱門論文排行榜，支援排行類型、年度與筆數限制
      parameters:
        - name: type
          in: query
          description: 排行類型（全文授權 total、被引用數 reference、被點閱數 view、全文下載數 download）
          required: true
          schema:
            type: string
            enum: [total, reference, view, download]
        - name: year
          in: query
          description: 年度（如 113、112、111）
          required: false
          schema:
            type: integer
            example: 113
        - name: limit
          in: query
          description: 限制回傳最大筆數（預設 10，最大 100）
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
      responses:
        '200':
          description: 成功取得排行榜
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        rank:
                          type: integer
                          description: 排名
                          example: 1
                        school:
                          type: string
                          description: 學校名稱
                          example: "國立臺灣大學"
                        count:
                          type: integer
                          description: 數量
                          example: 12456

        '400':
          description: 錯誤的請求參數
        '500':
          description: 伺服器錯誤
  /api/ranking/detailedfields:
    get:
      summary: 取得論文「學類」熱門排行榜
      description: 取得各校熱門論文排行榜，支援排行類型、年度與筆數限制
      parameters:
        - name: type
          in: query
          description: 排行類型（全文授權 total、被引用數 reference、被點閱數 view、全文下載數 download）
          required: true
          schema:
            type: string
            enum: [total, reference, view, download]
        - name: year
          in: query
          description: 年度（如 113、112、111）
          required: false
          schema:
            type: integer
            example: 113
        - name: limit
          in: query
          description: 限制回傳最大筆數（預設 10，最大 100）
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
      responses:
        '200':
          description: 成功取得排行榜
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        rank:
                          type: integer
                          description: 排名
                          example: 1
                        school:
                          type: string
                          description: 學校名稱
                          example: "國立臺灣大學"
                        count:
                          type: integer
                          description: 數量
                          example: 12456

        '400':
          description: 錯誤的請求參數
        '500':
          description: 伺服器錯誤


components: {}
