# swagger.yaml

openapi: 3.0.3
info:
  title: 「新世代博碩士論文網」論文 API
  description: 提供單篇論文詳細內容
  version: 1.0.0
servers:
  - url: ndltd.ncl.edu.tw
paths:
  /api/theses/{id}:
    get:
      summary: 取得單篇論文詳細內容
      description: 依論文 id 取得詳細內容
      parameters:
        - name: id
          in: path
          required: true
          description: 論文唯一識別碼
          schema:
            type: string
            example: "1"
      responses:
        '200':
          description: 成功取得論文內容
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: 論文唯一識別碼
                    example: "1"
                  title:
                    type: string
                    description: 論文標題
                    example: "台灣博碩士論文網發展現況與展望"
                  author:
                    type: string
                    description: 作者
                    example: "王小明"
                  school:
                    type: string
                    description: 學校
                    example: "國立臺灣大學"
                  degree:
                    type: string
                    description: 學位
                    example: "碩士"
                  year:
                    type: integer
                    description: 年度
                    example: 113
                  abstract:
                    type: string
                    description: 摘要
                    example: "本論文探討台灣博碩士論文網的發展現況與未來展望..."
                  abstractEn:
                    type: string
                    description: 英文摘要
                    example: "With the rapid development of artificial..."
                  keywords:
                    type: array
                    description: 關鍵字
                    items:
                      type: string
                    example: ["論文網", "台灣", "Open Access"]
                  keywordsEn:
                    type: array
                    description: 英文關鍵字
                    items:
                      type: string
                    example: ["Natural Language Processing", "Open Access"]
                  fullTextUrl:
                    type: string
                    description: 全文下載連結
                    example: "https://thesis-pulse.lovable.app/files/1.pdf"
                  referenceCount:
                    type: integer
                    description: 被引用數
                    example: 25
                  viewCount:
                    type: integer
                    description: 被點閱數
                    example: 1200
                  downloadCount:
                    type: integer
                    description: 下載數
                    example: 800
        '404':
          description: 找不到該論文
        '400':
          description: 錯誤的請求參數
        '500':
          description: 伺服器錯誤

  /api/theses/search:
    get:
      summary: 搜尋論文
      description: 依多種條件（含進階檢索）搜尋論文，回傳論文列表
      parameters:
        - name: keyword
          in: query
          description: 關鍵字（標題、摘要、關鍵字等模糊搜尋）
          required: false
          schema:
            type: string
            example: "Open Access"
        - name: school
          in: query
          description: 學校名稱
          required: false
          schema:
            type: string
            example: "國立臺灣大學"
        - name: author
          in: query
          description: 作者
          required: false
          schema:
            type: string
            example: "王小明"
        - name: degree
          in: query
          description: 學位（碩士/博士/其他）
          required: false
          schema:
            type: string
            enum: [碩士, 博士, 其他]
        - name: type
          in: query
          description: 論文類型（如學術、技術、專利等）
          required: false
          schema:
            type: string
            example: "學術"
        - name: college
          in: query
          description: 學院
          required: false
          schema:
            type: string
            example: "工學院"
        - name: department
          in: query
          description: 系所
          required: false
          schema:
            type: string
            example: "資訊工程學系"
        - name: advisor
          in: query
          description: 指導教授
          required: false
          schema:
            type: string
            example: "陳大明"
        - name: language
          in: query
          description: 論文語言
          required: false
          schema:
            type: string
            example: "中文"
        - name: fullTextAvailable
          in: query
          description: 是否有全文（true/false）
          required: false
          schema:
            type: boolean
            example: true
        - name: year
          in: query
          description: 年度
          required: false
          schema:
            type: integer
            example: 113
        - name: referenceCountMin
          in: query
          description: 被引用數最小值
          required: false
          schema:
            type: integer
            example: 10
        - name: referenceCountMax
          in: query
          description: 被引用數最大值
          required: false
          schema:
            type: integer
            example: 100
        - name: downloadCountMin
          in: query
          description: 下載數最小值
          required: false
          schema:
            type: integer
            example: 50
        - name: downloadCountMax
          in: query
          description: 下載數最大值
          required: false
          schema:
            type: integer
            example: 500
        - name: viewCountMin
          in: query
          description: 點閱數最小值
          required: false
          schema:
            type: integer
            example: 100
        - name: viewCountMax
          in: query
          description: 點閱數最大值
          required: false
          schema:
            type: integer
            example: 2000
        - name: sort
          in: query
          description: 排序方式（viewCount、downloadCount、year、relevance）
          required: false
          schema:
            type: string
            enum: [viewCount, downloadCount, year, relevance]
            example: "relevance"
        - name: limit
          in: query
          description: 限制回傳最大筆數（預設 10，最大 100）
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
      responses:
        '200':
          description: 成功取得搜尋結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: 論文唯一識別碼
                          example: "1"
                        title:
                          type: string
                          description: 論文標題
                          example: "台灣博碩士論文網發展現況與展望"
                        author:
                          type: string
                          description: 作者
                          example: "王小明"
                        school:
                          type: string
                          description: 學校
                          example: "國立臺灣大學"
                        degree:
                          type: string
                          description: 學位
                          example: "碩士"
                        type:
                          type: string
                          description: 論文類型
                          example: "學術"
                        college:
                          type: string
                          description: 學院
                          example: "工學院"
                        department:
                          type: string
                          description: 系所
                          example: "資訊工程學系"
                        advisor:
                          type: string
                          description: 指導教授
                          example: "陳大明"
                        language:
                          type: string
                          description: 論文語言
                          example: "中文"
                        year:
                          type: integer
                          description: 年度
                          example: 113
                        abstract:
                          type: string
                          description: 摘要
                          example: "本論文探討台灣博碩士論文網的發展現況與未來展望..."
                        keywords:
                          type: array
                          description: 關鍵字
                          items:
                            type: string
                          example: ["論文網", "台灣", "Open Access"]
                        fullTextAvailable:
                          type: boolean
                          description: 是否有全文
                          example: true
                        viewCount:
                          type: integer
                          description: 被點閱數
                          example: 1200
                        downloadCount:
                          type: integer
                          description: 下載數
                          example: 800
                        referenceCount:
                          type: integer
                          description: 被引用數
                          example: 25
                example:
                  data:
                    - id: "1"
                      title: "台灣博碩士論文網發展現況與展望"
                      author: "王小明"
                      school: "國立臺灣大學"
                      degree: "碩士"
                      type: "學術"
                      college: "工學院"
                      department: "資訊工程學系"
                      advisor: "陳大明"
                      language: "中文"
                      year: 113
                      abstract: "本論文探討台灣博碩士論文網的發展現況與未來展望..."
                      keywords: ["論文網", "台灣", "Open Access"]
                      fullTextAvailable: true
                      viewCount: 1200
                      downloadCount: 800
                      referenceCount: 25
                    - id: "2"
                      title: "AI在論文檢索中的應用"
                      author: "李小華"
                      school: "國立成功大學"
                      degree: "博士"
                      type: "技術"
                      college: "資訊學院"
                      department: "人工智慧研究所"
                      advisor: "林教授"
                      language: "中文"
                      year: 112
                      abstract: "本研究分析AI技術在論文檢索效率上的提升..."
                      keywords: ["AI", "論文檢索", "效率"]
                      fullTextAvailable: false
                      viewCount: 950
                      downloadCount: 600
                      referenceCount: 10
        '400':
          description: 錯誤的請求參數
        '500':
          description: 伺服器錯誤
components: {}
