openapi: 3.0.3
info:
  title: 大學論文系統 資料庫結構
  description: |
    # 大學論文系統 資料表結構

    ## 1. 使用者管理

    ### 1.1 系統管理員 (admins)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 唯一識別碼 | PRIMARY KEY |
    | username | VARCHAR(50) | 帳號 | UNIQUE, NOT NULL |
    | password_hash | VARCHAR(255) | 密碼雜湊 | NOT NULL |
    | name | VARCHAR(100) | 姓名 | NOT NULL |
    | email | VARCHAR(255) | 電子郵件 | UNIQUE, NOT NULL |
    | role | ENUM | 角色 | 'superadmin','admin','staff' |
    | permissions | JSON | 權限設定 |  |
    | status | ENUM | 狀態 | 'active','inactive','suspended' |
    | last_login | TIMESTAMP | 最後登入時間 |  |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |

    ### 1.2 學校管理員 (school_admins)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 唯一識別碼 | PRIMARY KEY |
    | school_id | VARCHAR(50) | 所屬學校 | FOREIGN KEY |
    | username | VARCHAR(50) | 帳號 | UNIQUE, NOT NULL |
    | password_hash | VARCHAR(255) | 密碼雜湊 | NOT NULL |
    | name | VARCHAR(100) | 姓名 | NOT NULL |
    | email | VARCHAR(255) | 電子郵件 | UNIQUE, NOT NULL |
    | role | ENUM | 角色 | 'admin','reviewer','staff' |
    | permissions | JSON | 權限設定 |  |
    | status | ENUM | 狀態 | 'active','inactive','suspended' |
    | last_login | TIMESTAMP | 最後登入時間 |  |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |

    ### 1.3 學生 (students)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 學號 | PRIMARY KEY |
    | school_id | VARCHAR(50) | 所屬學校 | FOREIGN KEY |
    | department_id | VARCHAR(50) | 所屬系所 | FOREIGN KEY |
    | name | VARCHAR(100) | 姓名 | NOT NULL |
    | email | VARCHAR(255) | 電子郵件 | UNIQUE, NOT NULL |
    | degree | ENUM | 學位 | 'bachelor','master','phd' |
    | grade | VARCHAR(20) | 年級 |  |
    | status | ENUM | 狀態 | 'active','graduated','suspended','withdrawn' |
    | last_login | TIMESTAMP | 最後登入時間 |  |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |

    ## 2. 學校與系所管理

    ### 2.1 學校 (schools)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 學校代碼 | PRIMARY KEY |
    | name | VARCHAR(200) | 學校名稱 | NOT NULL |
    | english_name | VARCHAR(300) | 英文校名 |  |
    | type | ENUM | 學校類型 | 'national','private','technical','other' |
    | region | VARCHAR(50) | 地區 | NOT NULL |
    | address | TEXT | 地址 |  |
    | phone | VARCHAR(20) | 電話 |  |
    | website | VARCHAR(255) | 網站 |  |
    | email | VARCHAR(255) | 聯絡信箱 |  |
    | status | ENUM | 狀態 | 'active','inactive','suspended' |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |

    ### 2.2 系所 (departments)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 系所代碼 | PRIMARY KEY |
    | school_id | VARCHAR(50) | 所屬學校 | FOREIGN KEY |
    | name | VARCHAR(200) | 系所名稱 | NOT NULL |
    | english_name | VARCHAR(300) | 英文系所名 |  |
    | college | VARCHAR(100) | 學院 |  |
    | degree_types | JSON | 學位類別 |  |
    | status | ENUM | 狀態 | 'active','inactive' |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |

    ## 3. 論文管理

    ### 3.1 論文 (theses)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 論文編號 | PRIMARY KEY |
    | student_id | VARCHAR(50) | 學生ID | FOREIGN KEY |
    | school_id | VARCHAR(50) | 學校ID | FOREIGN KEY |
    | department_id | VARCHAR(50) | 系所ID | FOREIGN KEY |
    | title | TEXT | 論文標題 | NOT NULL |
    | english_title | TEXT | 英文標題 |  |
    | author | VARCHAR(200) | 作者 | NOT NULL |
    | advisor | VARCHAR(200) | 指導教授 |  |
    | co_advisors | JSON | 共同指導教授 |  |
    | keywords | JSON | 關鍵字 |  |
    | abstract | LONGTEXT | 摘要 |  |
    | english_abstract | LONGTEXT | 英文摘要 |  |
    | degree | ENUM | 學位 | 'bachelor','master','phd' |
    | year | INT | 學年度 | NOT NULL |
    | semester | ENUM | 學期 | '1','2' |
    | language | VARCHAR(50) | 論文語言 |  |
    | page_count | INT | 頁數 |  |
    | file_url | VARCHAR(500) | 檔案URL |  |
    | file_size | BIGINT | 檔案大小(bytes) |  |
    | file_format | VARCHAR(20) | 檔案格式 |  |
    | status | ENUM | 狀態 | 'draft','submitted','reviewing','approved','rejected','published' |
    | rejection_reason | TEXT | 退件原因 |  |
    | published_at | TIMESTAMP | 公開時間 |  |
    | view_count | INT | 瀏覽次數 | DEFAULT 0 |
    | download_count | INT | 下載次數 | DEFAULT 0 |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |

    ### 3.2 論文審查記錄 (thesis_reviews)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 記錄ID | PRIMARY KEY |
    | thesis_id | VARCHAR(50) | 論文ID | FOREIGN KEY |
    | reviewer_id | VARCHAR(50) | 審查者ID | FOREIGN KEY |
    | status | ENUM | 審查狀態 | 'pending','approved','rejected' |
    | comments | TEXT | 審查意見 |  |
    | reviewed_at | TIMESTAMP | 審查時間 |  |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |

    ## 4. 主題策展管理

    ### 4.1 主題策展 (exhibitions)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 策展ID | PRIMARY KEY |
    | title | VARCHAR(200) | 策展標題 | NOT NULL |
    | subtitle | VARCHAR(500) | 副標題 |  |
    | description | TEXT | 策展說明 |  |
    | cover_image | VARCHAR(500) | 封面圖片URL |  |
    | category | ENUM | 分類 | 'featured','discipline','topic','research' |
    | tags | JSON | 標籤 |  |
    | is_featured | BOOLEAN | 是否精選 | DEFAULT FALSE |
    | status | ENUM | 狀態 | 'draft','published','archived' |
    | start_date | DATE | 開始日期 |  |
    | end_date | DATE | 結束日期 |  |
    | created_by | VARCHAR(50) | 建立者 | FOREIGN KEY |
    | updated_by | VARCHAR(50) | 更新者 | FOREIGN KEY |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |

    ### 4.2 策展論文 (exhibition_theses)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 記錄ID | PRIMARY KEY |
    | exhibition_id | VARCHAR(50) | 策展ID | FOREIGN KEY |
    | thesis_id | VARCHAR(50) | 論文ID | FOREIGN KEY |
    | sort_order | INT | 排序 | DEFAULT 0 |
    | notes | TEXT | 備註 |  |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |

    ## 5. 系統設定

    ### 5.1 系統設定 (system_settings)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 設定ID | PRIMARY KEY |
    | setting_key | VARCHAR(100) | 設定鍵 | UNIQUE, NOT NULL |
    | setting_value | TEXT | 設定值 |  |
    | data_type | ENUM | 資料類型 | 'string','integer','boolean','json' |
    | category | VARCHAR(50) | 分類 |  |
    | description | TEXT | 說明 |  |
    | is_public | BOOLEAN | 是否公開 | DEFAULT FALSE |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |

    ### 5.2 論文設定 (thesis_settings)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | VARCHAR(50) | 設定ID | PRIMARY KEY |
    | school_id | VARCHAR(50) | 學校ID | FOREIGN KEY |
    | department_id | VARCHAR(50) | 系所ID | FOREIGN KEY |
    | setting_key | VARCHAR(100) | 設定鍵 | NOT NULL |
    | setting_value | TEXT | 設定值 |  |
    | data_type | ENUM | 資料類型 | 'string','integer','boolean','json' |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |
    | updated_at | TIMESTAMP | 更新時間 | ON UPDATE CURRENT_TIMESTAMP |
    | UNIQUE(school_id, department_id, setting_key) |  |  |  |

    ## 6. 操作記錄

    ### 6.1 系統日誌 (system_logs)
    | 欄位名稱 | 資料型態 | 說明 | 約束 |
    |---------|---------|------|------|
    | id | BIGINT | 日誌ID | AUTO_INCREMENT, PRIMARY KEY |
    | user_id | VARCHAR(50) | 使用者ID |  |
    | user_type | ENUM | 使用者類型 | 'admin','school_admin','student' |
    | action | VARCHAR(100) | 操作動作 | NOT NULL |
    | entity_type | VARCHAR(50) | 操作實體類型 |  |
    | entity_id | VARCHAR(50) | 操作實體ID |  |
    | ip_address | VARCHAR(45) | IP位址 |  |
    | user_agent | TEXT | 使用者代理 |  |
    | metadata | JSON | 額外資料 |  |
    | created_at | TIMESTAMP | 建立時間 | DEFAULT CURRENT_TIMESTAMP |

    ## 資料表關係

    1. **school_admins.school_id** → **schools.id**
       - 學校管理員屬於一個學校
       - 一個學校可以有多個學校管理員

    2. **students.school_id** → **schools.id**
       - 學生屬於一個學校
       - 一個學校可以有多個學生

    3. **students.department_id** → **departments.id**
       - 學生屬於一個系所
       - 一個系所可以有多個學生

    4. **departments.school_id** → **schools.id**
       - 系所屬於一個學校
       - 一個學校可以有多個系所

    5. **theses.student_id** → **students.id**
       - 論文屬於一個學生
       - 一個學生可以有多篇論文

    6. **theses.school_id** → **schools.id**
       - 論文屬於一個學校
       - 一個學校可以有多篇論文

    7. **theses.department_id** → **departments.id**
       - 論文屬於一個系所
       - 一個系所可以有多篇論文

    8. **thesis_reviews.thesis_id** → **theses.id**
       - 審查記錄屬於一篇論文
       - 一篇論文可以有多筆審查記錄

    9. **exhibition_theses.exhibition_id** → **exhibitions.id**
       - 策展論文關聯到一個策展
       - 一個策展可以關聯多篇論文

    10. **exhibition_theses.thesis_id** → **theses.id**
        - 策展論文關聯到一篇論文
        - 一篇論文可以關聯到多個策展

    11. **thesis_settings.school_id** → **schools.id**
        - 論文設定可以關聯到一個學校
        - 一個學校可以有多個論文設定

    12. **thesis_settings.department_id** → **departments.id**
        - 論文設定可以關聯到一個系所
        - 一個系所可以有多個論文設定

    這個資料庫設計涵蓋了大學論文系統的主要功能模組，包括使用者管理、學校系所管理、論文管理、主題策展、系統設定以及操作記錄等核心功能。

# 以下為 API 端點定義
paths:
  # 這裡可以添加 API 端點定義
  /example:
    get:
      summary: 範例 API 端點
      description: 這是一個範例 API 端點
      responses:
        '200':
          description: 成功回應

# 定義元件（可選）
components:
  schemas:
    # 可以在這裡定義資料模型
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
